version: '3.9'

services:
  nginx: 
    image: nginx:stable-alpine
    ports:
      - 80:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ../:/var/www/html
      
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=firstapp
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306

    volumes:
      - ./db:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - 81:80
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - PMA_HOST=mysql
      - PMA_USER=admin
      - PMA_PASSWORD=root
    depends_on:
      - mysql
  php:
    build: 
      context: php
      dockerfile: php.dockerfile
    volumes:
      - ../:/var/www/html